--------------------------------------------------------
--  File created - Sunday-June-11-2023   
--------------------------------------------------------
DROP TABLE "SYSTEM"."H_INVENTORY" cascade constraints;
DROP TABLE "SYSTEM"."BRANCH" cascade constraints;
DROP TABLE "SYSTEM"."H_PRODUCT" cascade constraints;
--------------------------------------------------------
--  DDL for Table H_INVENTORY
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."H_INVENTORY" 
   (	"INVENTORY_ID" NUMBER, 
	"QUANTITY" NUMBER, 
	"LASTUPDATE" TIMESTAMP (6), 
	"PRODUCT_ID" NUMBER, 
	"BRANCH_ID" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table BRANCH
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."BRANCH" 
   (	"BRANCH_ID" NUMBER, 
	"BRANCH_NAME" VARCHAR2(255 BYTE), 
	"LOCATION" VARCHAR2(255 BYTE), 
	"TIMEZONE" VARCHAR2(255 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table H_PRODUCT
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."H_PRODUCT" 
   (	"PRODUCT_ID" NUMBER, 
	"NAME" VARCHAR2(255 BYTE), 
	"DESCRIPTION" VARCHAR2(1000 BYTE), 
	"PRICE" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.H_INVENTORY
SET DEFINE OFF;
Insert into SYSTEM.H_INVENTORY (INVENTORY_ID,QUANTITY,LASTUPDATE,PRODUCT_ID,BRANCH_ID) values (1,10,to_timestamp('10-JUN-23 09.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),1,1);
Insert into SYSTEM.H_INVENTORY (INVENTORY_ID,QUANTITY,LASTUPDATE,PRODUCT_ID,BRANCH_ID) values (5,3,to_timestamp('18-JUN-23 02.00.00.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),5,5);
Insert into SYSTEM.H_INVENTORY (INVENTORY_ID,QUANTITY,LASTUPDATE,PRODUCT_ID,BRANCH_ID) values (2,5,to_timestamp('11-JUN-23 02.00.00.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),2,2);
Insert into SYSTEM.H_INVENTORY (INVENTORY_ID,QUANTITY,LASTUPDATE,PRODUCT_ID,BRANCH_ID) values (5,3,to_timestamp('18-JUN-23 02.00.00.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),5,5);
Insert into SYSTEM.H_INVENTORY (INVENTORY_ID,QUANTITY,LASTUPDATE,PRODUCT_ID,BRANCH_ID) values (6,5,to_timestamp('20-JUN-23 10.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),6,6);
Insert into SYSTEM.H_INVENTORY (INVENTORY_ID,QUANTITY,LASTUPDATE,PRODUCT_ID,BRANCH_ID) values (7,10,to_timestamp('25-JUN-23 02.30.00.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),7,7);
Insert into SYSTEM.H_INVENTORY (INVENTORY_ID,QUANTITY,LASTUPDATE,PRODUCT_ID,BRANCH_ID) values (8,5,to_timestamp('27-JUN-23 11.45.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),8,8);
Insert into SYSTEM.H_INVENTORY (INVENTORY_ID,QUANTITY,LASTUPDATE,PRODUCT_ID,BRANCH_ID) values (9,10,to_timestamp('30-JUN-23 09.15.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),9,9);
Insert into SYSTEM.H_INVENTORY (INVENTORY_ID,QUANTITY,LASTUPDATE,PRODUCT_ID,BRANCH_ID) values (10,15,to_timestamp('05-JUL-23 10.30.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),10,10);
--------------------------------------------------------
--  Ref Constraints for Table H_INVENTORY
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."H_INVENTORY" ADD FOREIGN KEY ("PRODUCT_ID")
	  REFERENCES "SYSTEM"."H_PRODUCT" ("PRODUCT_ID") ENABLE;
  ALTER TABLE "SYSTEM"."H_INVENTORY" ADD FOREIGN KEY ("BRANCH_ID")
	  REFERENCES "SYSTEM"."BRANCH" ("BRANCH_ID") ENABLE;
