--------------------------------------------------------
--  File created - Sunday-June-11-2023   
--------------------------------------------------------
DROP TABLE "SYSTEM"."H_PRODUCT" cascade constraints;
DROP TABLE "SYSTEM"."H_PRODUCT" cascade constraints;
--------------------------------------------------------
--  DDL for Table H_PRODUCT
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."H_PRODUCT" 
   (	"PRODUCT_ID" NUMBER, 
	"NAME" VARCHAR2(255 BYTE), 
	"DESCRIPTION" VARCHAR2(1000 BYTE), 
	"PRICE" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table H_PRODUCT
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."H_PRODUCT" 
   (	"PRODUCT_ID" NUMBER, 
	"NAME" VARCHAR2(255 BYTE), 
	"DESCRIPTION" VARCHAR2(1000 BYTE), 
	"PRICE" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.H_PRODUCT
SET DEFINE OFF;
Insert into SYSTEM.H_PRODUCT (PRODUCT_ID,NAME,DESCRIPTION,PRICE) values (1,'Product A','Description for Product A',9.99);
Insert into SYSTEM.H_PRODUCT (PRODUCT_ID,NAME,DESCRIPTION,PRICE) values (5,'Product E','Description for Product E',49.99);
Insert into SYSTEM.H_PRODUCT (PRODUCT_ID,NAME,DESCRIPTION,PRICE) values (2,'Product B','Description for Product B',19.99);
Insert into SYSTEM.H_PRODUCT (PRODUCT_ID,NAME,DESCRIPTION,PRICE) values (6,'Product F','Description for Product F',79.99);
Insert into SYSTEM.H_PRODUCT (PRODUCT_ID,NAME,DESCRIPTION,PRICE) values (7,'Product G','Description for Product G',99.99);
Insert into SYSTEM.H_PRODUCT (PRODUCT_ID,NAME,DESCRIPTION,PRICE) values (8,'Product H','Description for Product H',149.99);
Insert into SYSTEM.H_PRODUCT (PRODUCT_ID,NAME,DESCRIPTION,PRICE) values (9,'Product I','Description for Product I',199.99);
Insert into SYSTEM.H_PRODUCT (PRODUCT_ID,NAME,DESCRIPTION,PRICE) values (10,'Product II','Description for Product II',149.99);
--------------------------------------------------------
--  DDL for Index SYS_C007977
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C007977" ON "SYSTEM"."H_PRODUCT" ("PRODUCT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table H_PRODUCT
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."H_PRODUCT" ADD PRIMARY KEY ("PRODUCT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
