--------------------------------------------------------
--  File created - Sunday-June-11-2023   
--------------------------------------------------------
DROP TABLE "SYSTEM"."STOCK_ODER_ITEM" cascade constraints;
DROP TABLE "SYSTEM"."STOCK_ORDER" cascade constraints;
DROP TABLE "SYSTEM"."H_PRODUCT" cascade constraints;
DROP TABLE "SYSTEM"."STOCK_ORDER" cascade constraints;
DROP TABLE "SYSTEM"."BRANCH" cascade constraints;
DROP TABLE "SYSTEM"."STOCK_ODER_ITEM" cascade constraints;
--------------------------------------------------------
--  DDL for Table STOCK_ODER_ITEM
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."STOCK_ODER_ITEM" 
   (	"STOCK_ORDER_ITEM_ID" NUMBER, 
	"QUANTITY" NUMBER, 
	"STOCK_ORDER_ID" NUMBER, 
	"PRODUCT_ID" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table STOCK_ORDER
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."STOCK_ORDER" 
   (	"STOCK_ORDER_ID" NUMBER, 
	"PLACEMENT_DATE" TIMESTAMP (6), 
	"BRANCH_ID" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table H_PRODUCT
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."H_PRODUCT" 
   (	"PRODUCT_ID" NUMBER, 
	"NAME" VARCHAR2(255 BYTE), 
	"DESCRIPTION" VARCHAR2(1000 BYTE), 
	"PRICE" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table STOCK_ORDER
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."STOCK_ORDER" 
   (	"STOCK_ORDER_ID" NUMBER, 
	"PLACEMENT_DATE" TIMESTAMP (6), 
	"BRANCH_ID" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table BRANCH
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."BRANCH" 
   (	"BRANCH_ID" NUMBER, 
	"BRANCH_NAME" VARCHAR2(255 BYTE), 
	"LOCATION" VARCHAR2(255 BYTE), 
	"TIMEZONE" VARCHAR2(255 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table STOCK_ODER_ITEM
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."STOCK_ODER_ITEM" 
   (	"STOCK_ORDER_ITEM_ID" NUMBER, 
	"QUANTITY" NUMBER, 
	"STOCK_ORDER_ID" NUMBER, 
	"PRODUCT_ID" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.STOCK_ODER_ITEM
SET DEFINE OFF;
Insert into SYSTEM.STOCK_ODER_ITEM (STOCK_ORDER_ITEM_ID,QUANTITY,STOCK_ORDER_ID,PRODUCT_ID) values (1,10,1,1);
Insert into SYSTEM.STOCK_ODER_ITEM (STOCK_ORDER_ITEM_ID,QUANTITY,STOCK_ORDER_ID,PRODUCT_ID) values (5,3,5,5);
Insert into SYSTEM.STOCK_ODER_ITEM (STOCK_ORDER_ITEM_ID,QUANTITY,STOCK_ORDER_ID,PRODUCT_ID) values (2,5,2,2);
Insert into SYSTEM.STOCK_ODER_ITEM (STOCK_ORDER_ITEM_ID,QUANTITY,STOCK_ORDER_ID,PRODUCT_ID) values (6,5,6,6);
Insert into SYSTEM.STOCK_ODER_ITEM (STOCK_ORDER_ITEM_ID,QUANTITY,STOCK_ORDER_ID,PRODUCT_ID) values (7,10,7,7);
Insert into SYSTEM.STOCK_ODER_ITEM (STOCK_ORDER_ITEM_ID,QUANTITY,STOCK_ORDER_ID,PRODUCT_ID) values (8,5,8,8);
Insert into SYSTEM.STOCK_ODER_ITEM (STOCK_ORDER_ITEM_ID,QUANTITY,STOCK_ORDER_ID,PRODUCT_ID) values (9,10,9,9);
Insert into SYSTEM.STOCK_ODER_ITEM (STOCK_ORDER_ITEM_ID,QUANTITY,STOCK_ORDER_ID,PRODUCT_ID) values (10,15,10,10);
REM INSERTING into SYSTEM.STOCK_ORDER
SET DEFINE OFF;
Insert into SYSTEM.STOCK_ORDER (STOCK_ORDER_ID,PLACEMENT_DATE,BRANCH_ID) values (1,to_timestamp('10-JUN-23 09.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),1);
Insert into SYSTEM.STOCK_ORDER (STOCK_ORDER_ID,PLACEMENT_DATE,BRANCH_ID) values (5,to_timestamp('18-JUN-23 02.00.00.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),5);
Insert into SYSTEM.STOCK_ORDER (STOCK_ORDER_ID,PLACEMENT_DATE,BRANCH_ID) values (2,to_timestamp('11-JUN-23 02.00.00.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),2);
Insert into SYSTEM.STOCK_ORDER (STOCK_ORDER_ID,PLACEMENT_DATE,BRANCH_ID) values (6,to_timestamp('20-JUN-23 10.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),6);
Insert into SYSTEM.STOCK_ORDER (STOCK_ORDER_ID,PLACEMENT_DATE,BRANCH_ID) values (7,to_timestamp('25-JUN-23 02.30.00.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),7);
Insert into SYSTEM.STOCK_ORDER (STOCK_ORDER_ID,PLACEMENT_DATE,BRANCH_ID) values (8,to_timestamp('27-JUN-23 11.45.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),8);
Insert into SYSTEM.STOCK_ORDER (STOCK_ORDER_ID,PLACEMENT_DATE,BRANCH_ID) values (9,to_timestamp('30-JUN-23 09.15.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),9);
Insert into SYSTEM.STOCK_ORDER (STOCK_ORDER_ID,PLACEMENT_DATE,BRANCH_ID) values (10,to_timestamp('05-JUL-23 10.30.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),10);
--------------------------------------------------------
--  DDL for Index SYS_C007980
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C007980" ON "SYSTEM"."STOCK_ODER_ITEM" ("STOCK_ORDER_ITEM_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007978
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C007978" ON "SYSTEM"."STOCK_ORDER" ("STOCK_ORDER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table STOCK_ODER_ITEM
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."STOCK_ODER_ITEM" ADD PRIMARY KEY ("STOCK_ORDER_ITEM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table STOCK_ORDER
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."STOCK_ORDER" ADD PRIMARY KEY ("STOCK_ORDER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table STOCK_ODER_ITEM
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."STOCK_ODER_ITEM" ADD FOREIGN KEY ("STOCK_ORDER_ID")
	  REFERENCES "SYSTEM"."STOCK_ORDER" ("STOCK_ORDER_ID") ENABLE;
  ALTER TABLE "SYSTEM"."STOCK_ODER_ITEM" ADD FOREIGN KEY ("PRODUCT_ID")
	  REFERENCES "SYSTEM"."H_PRODUCT" ("PRODUCT_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table STOCK_ORDER
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."STOCK_ORDER" ADD FOREIGN KEY ("BRANCH_ID")
	  REFERENCES "SYSTEM"."BRANCH" ("BRANCH_ID") ENABLE;
