--------------------------------------------------------
--  File created - Sunday-June-11-2023   
--------------------------------------------------------
DROP TABLE "SYSTEM"."CUSTOMER_PURCHASE" cascade constraints;
DROP TABLE "SYSTEM"."H_CUSTOMER" cascade constraints;
DROP TABLE "SYSTEM"."CUSTOMER_PURCHASE" cascade constraints;
--------------------------------------------------------
--  DDL for Table CUSTOMER_PURCHASE
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."CUSTOMER_PURCHASE" 
   (	"CUSTOMER_PURCHASE_ID" NUMBER, 
	"PURCHASED_DATE" TIMESTAMP (6), 
	"PAYMENT_STATUS" VARCHAR2(255 BYTE), 
	"PAYMENT_METHOD" VARCHAR2(255 BYTE), 
	"CUSTOMER_ID" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table H_CUSTOMER
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."H_CUSTOMER" 
   (	"CUSTOMER_ID" NUMBER, 
	"NAME" VARCHAR2(255 BYTE), 
	"ADDRESS" VARCHAR2(255 BYTE), 
	"CONTACT_NO" VARCHAR2(255 BYTE), 
	"EMAIL" VARCHAR2(255 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CUSTOMER_PURCHASE
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."CUSTOMER_PURCHASE" 
   (	"CUSTOMER_PURCHASE_ID" NUMBER, 
	"PURCHASED_DATE" TIMESTAMP (6), 
	"PAYMENT_STATUS" VARCHAR2(255 BYTE), 
	"PAYMENT_METHOD" VARCHAR2(255 BYTE), 
	"CUSTOMER_ID" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.CUSTOMER_PURCHASE
SET DEFINE OFF;
Insert into SYSTEM.CUSTOMER_PURCHASE (CUSTOMER_PURCHASE_ID,PURCHASED_DATE,PAYMENT_STATUS,PAYMENT_METHOD,CUSTOMER_ID) values (1,to_timestamp('10-JUN-23 12.00.00.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'Paid','Credit Card',1);
Insert into SYSTEM.CUSTOMER_PURCHASE (CUSTOMER_PURCHASE_ID,PURCHASED_DATE,PAYMENT_STATUS,PAYMENT_METHOD,CUSTOMER_ID) values (5,to_timestamp('19-JUN-23 09.30.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Paid','Credit Card',5);
Insert into SYSTEM.CUSTOMER_PURCHASE (CUSTOMER_PURCHASE_ID,PURCHASED_DATE,PAYMENT_STATUS,PAYMENT_METHOD,CUSTOMER_ID) values (2,to_timestamp('12-JUN-23 10.00.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Pending','Cash',2);
Insert into SYSTEM.CUSTOMER_PURCHASE (CUSTOMER_PURCHASE_ID,PURCHASED_DATE,PAYMENT_STATUS,PAYMENT_METHOD,CUSTOMER_ID) values (6,to_timestamp('21-JUN-23 03.45.00.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'Pending','Cash',6);
Insert into SYSTEM.CUSTOMER_PURCHASE (CUSTOMER_PURCHASE_ID,PURCHASED_DATE,PAYMENT_STATUS,PAYMENT_METHOD,CUSTOMER_ID) values (7,to_timestamp('26-JUN-23 09.15.00.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),'Paid','Credit Card',7);
Insert into SYSTEM.CUSTOMER_PURCHASE (CUSTOMER_PURCHASE_ID,PURCHASED_DATE,PAYMENT_STATUS,PAYMENT_METHOD,CUSTOMER_ID) values (8,to_timestamp('28-JUN-23 03.20.00.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'Paid','Cash',8);
Insert into SYSTEM.CUSTOMER_PURCHASE (CUSTOMER_PURCHASE_ID,PURCHASED_DATE,PAYMENT_STATUS,PAYMENT_METHOD,CUSTOMER_ID) values (9,to_timestamp('01-JUL-23 02.45.00.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'Pending','Credit Card',9);
Insert into SYSTEM.CUSTOMER_PURCHASE (CUSTOMER_PURCHASE_ID,PURCHASED_DATE,PAYMENT_STATUS,PAYMENT_METHOD,CUSTOMER_ID) values (10,to_timestamp('06-JUL-23 03.20.00.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'Paid','Cash',10);
--------------------------------------------------------
--  DDL for Index SYS_C007988
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C007988" ON "SYSTEM"."CUSTOMER_PURCHASE" ("CUSTOMER_PURCHASE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CUSTOMER_PURCHASE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."CUSTOMER_PURCHASE" ADD PRIMARY KEY ("CUSTOMER_PURCHASE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CUSTOMER_PURCHASE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."CUSTOMER_PURCHASE" ADD FOREIGN KEY ("CUSTOMER_ID")
	  REFERENCES "SYSTEM"."H_CUSTOMER" ("CUSTOMER_ID") ENABLE;
