--------------------------------------------------------
--  File created - Sunday-June-11-2023   
--------------------------------------------------------
DROP TABLE "SYSTEM"."CUSTOMER_PURCHASE_ITEM" cascade constraints;
DROP TABLE "SYSTEM"."CUSTOMER_PURCHASE" cascade constraints;
DROP TABLE "SYSTEM"."H_PRODUCT" cascade constraints;
DROP TABLE "SYSTEM"."CUSTOMER_PURCHASE_ITEM" cascade constraints;
--------------------------------------------------------
--  DDL for Table CUSTOMER_PURCHASE_ITEM
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."CUSTOMER_PURCHASE_ITEM" 
   (	"CUSTOMER_PURCHASE_ITEM_ID" NUMBER, 
	"UNIT_PRICE" NUMBER, 
	"QUANTITY" NUMBER, 
	"PRODUCT_ID" NUMBER, 
	"CUSTOMER_PURCHASE_ID" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CUSTOMER_PURCHASE
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."CUSTOMER_PURCHASE" 
   (	"CUSTOMER_PURCHASE_ID" NUMBER, 
	"PURCHASED_DATE" TIMESTAMP (6), 
	"PAYMENT_STATUS" VARCHAR2(255 BYTE), 
	"PAYMENT_METHOD" VARCHAR2(255 BYTE), 
	"CUSTOMER_ID" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table H_PRODUCT
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."H_PRODUCT" 
   (	"PRODUCT_ID" NUMBER, 
	"NAME" VARCHAR2(255 BYTE), 
	"DESCRIPTION" VARCHAR2(1000 BYTE), 
	"PRICE" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CUSTOMER_PURCHASE_ITEM
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."CUSTOMER_PURCHASE_ITEM" 
   (	"CUSTOMER_PURCHASE_ITEM_ID" NUMBER, 
	"UNIT_PRICE" NUMBER, 
	"QUANTITY" NUMBER, 
	"PRODUCT_ID" NUMBER, 
	"CUSTOMER_PURCHASE_ID" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.CUSTOMER_PURCHASE_ITEM
SET DEFINE OFF;
Insert into SYSTEM.CUSTOMER_PURCHASE_ITEM (CUSTOMER_PURCHASE_ITEM_ID,UNIT_PRICE,QUANTITY,PRODUCT_ID,CUSTOMER_PURCHASE_ID) values (1,10.99,2,1,1);
Insert into SYSTEM.CUSTOMER_PURCHASE_ITEM (CUSTOMER_PURCHASE_ITEM_ID,UNIT_PRICE,QUANTITY,PRODUCT_ID,CUSTOMER_PURCHASE_ID) values (5,44.99,2,5,5);
Insert into SYSTEM.CUSTOMER_PURCHASE_ITEM (CUSTOMER_PURCHASE_ITEM_ID,UNIT_PRICE,QUANTITY,PRODUCT_ID,CUSTOMER_PURCHASE_ID) values (2,14.99,3,2,2);
Insert into SYSTEM.CUSTOMER_PURCHASE_ITEM (CUSTOMER_PURCHASE_ITEM_ID,UNIT_PRICE,QUANTITY,PRODUCT_ID,CUSTOMER_PURCHASE_ID) values (6,69.99,3,6,6);
Insert into SYSTEM.CUSTOMER_PURCHASE_ITEM (CUSTOMER_PURCHASE_ITEM_ID,UNIT_PRICE,QUANTITY,PRODUCT_ID,CUSTOMER_PURCHASE_ID) values (7,89.99,2,7,7);
Insert into SYSTEM.CUSTOMER_PURCHASE_ITEM (CUSTOMER_PURCHASE_ITEM_ID,UNIT_PRICE,QUANTITY,PRODUCT_ID,CUSTOMER_PURCHASE_ID) values (8,129.99,1,8,8);
Insert into SYSTEM.CUSTOMER_PURCHASE_ITEM (CUSTOMER_PURCHASE_ITEM_ID,UNIT_PRICE,QUANTITY,PRODUCT_ID,CUSTOMER_PURCHASE_ID) values (9,189.99,2,9,9);
Insert into SYSTEM.CUSTOMER_PURCHASE_ITEM (CUSTOMER_PURCHASE_ITEM_ID,UNIT_PRICE,QUANTITY,PRODUCT_ID,CUSTOMER_PURCHASE_ID) values (10,139.99,3,10,10);
--------------------------------------------------------
--  DDL for Index SYS_C007990
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C007990" ON "SYSTEM"."CUSTOMER_PURCHASE_ITEM" ("CUSTOMER_PURCHASE_ITEM_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CUSTOMER_PURCHASE_ITEM
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."CUSTOMER_PURCHASE_ITEM" ADD PRIMARY KEY ("CUSTOMER_PURCHASE_ITEM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CUSTOMER_PURCHASE_ITEM
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."CUSTOMER_PURCHASE_ITEM" ADD FOREIGN KEY ("PRODUCT_ID")
	  REFERENCES "SYSTEM"."H_PRODUCT" ("PRODUCT_ID") ENABLE;
  ALTER TABLE "SYSTEM"."CUSTOMER_PURCHASE_ITEM" ADD FOREIGN KEY ("CUSTOMER_PURCHASE_ID")
	  REFERENCES "SYSTEM"."CUSTOMER_PURCHASE" ("CUSTOMER_PURCHASE_ID") ENABLE;
