--------------------------------------------------------
--  File created - Sunday-June-11-2023   
--------------------------------------------------------
DROP TABLE "SYSTEM"."MANUFACTURE" cascade constraints;
DROP TABLE "SYSTEM"."MANUFACTURE" cascade constraints;
--------------------------------------------------------
--  DDL for Table MANUFACTURE
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."MANUFACTURE" 
   (	"MANUFACTURE_ID" NUMBER, 
	"MANUFACTURE_DETAILS" VARCHAR2(255 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MANUFACTURE
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."MANUFACTURE" 
   (	"MANUFACTURE_ID" NUMBER, 
	"MANUFACTURE_DETAILS" VARCHAR2(255 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.MANUFACTURE
SET DEFINE OFF;
Insert into SYSTEM.MANUFACTURE (MANUFACTURE_ID,MANUFACTURE_DETAILS) values (1,'Manufacturing details for product 1');
Insert into SYSTEM.MANUFACTURE (MANUFACTURE_ID,MANUFACTURE_DETAILS) values (5,'Manufacturing details for product 5');
Insert into SYSTEM.MANUFACTURE (MANUFACTURE_ID,MANUFACTURE_DETAILS) values (2,'Manufacturing details for product 2');
Insert into SYSTEM.MANUFACTURE (MANUFACTURE_ID,MANUFACTURE_DETAILS) values (6,'Manufacturing details for product 6');
Insert into SYSTEM.MANUFACTURE (MANUFACTURE_ID,MANUFACTURE_DETAILS) values (7,'Manufacturing details for product 7');
Insert into SYSTEM.MANUFACTURE (MANUFACTURE_ID,MANUFACTURE_DETAILS) values (8,'Manufacturing details for product 8');
Insert into SYSTEM.MANUFACTURE (MANUFACTURE_ID,MANUFACTURE_DETAILS) values (9,'Manufacturing details for product 9');
Insert into SYSTEM.MANUFACTURE (MANUFACTURE_ID,MANUFACTURE_DETAILS) values (10,'Manufacturing details for product 10');
--------------------------------------------------------
--  DDL for Index SYS_C007975
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C007975" ON "SYSTEM"."MANUFACTURE" ("MANUFACTURE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table MANUFACTURE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."MANUFACTURE" ADD PRIMARY KEY ("MANUFACTURE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
